spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wallet?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    properties:
        hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect       
    show-sql: true
server:
  port: 8081